# Generated by Django 4.1.7 on 2023-03-14 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='jobId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', related_query_name='job', to='questions.job'),
        ),
    ]
