# Generated by Django 4.1.7 on 2023-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_userid_examresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='examDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
