# Generated by Django 4.1.7 on 2023-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_examresult_job_alter_examresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
