# Generated by Django 4.1.7 on 2023-03-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Date joined'),
        ),
    ]
