# Generated by Django 4.1.7 on 2023-03-15 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='registered_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
